[package]
name = "blackmetal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
objc2 = "0.6.1"
objc2-metal = "0.3.1"
objc2-metal-kit = "0.3.1"
objc2-quartz-core = "0.3.1"
raw-window-handle = "0.6.2"
raw-window-metal = "1.1.0"
